baseURL: http://parrhall.com
languageCode: en-us
theme: github.com/setsevireon/photophobia

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 12 
googleAnalytics: ""

languages:
  en:
    title: parr hall - an open project notebook
    weight: 1
    contentDir: content/en
  fr:
    title: salle d'parr - un cahier projet ouvert
    weight: 2
    contentDir: content/fr

taxonomies:
  category: categories

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

params:
  favicon: null
  site_logo: null
  recent_posts_number: 12

markup:
  highlight:
    style: native